<?php
declare(strict_types=1);
require_once __DIR__.'/../auth/session.php';
require_login();
$id=(int)($_GET['id']??0);
$w=one("SELECT w.*,e.employee_number,e.full_name employee_name,e.position,d.department_name,t.type_name,v.version_number,es.printed_name employee_printed,es.signature_data employee_signature,es.signed_at employee_signed_at,ss.printed_name supervisor_printed,ss.signature_data supervisor_signature,ss.signed_at supervisor_signed_at FROM dbo.acd_mw_waivers w JOIN dbo.acd_mw_employees e ON e.employee_id=w.employee_id LEFT JOIN dbo.acd_mw_departments d ON d.department_id=e.department_id JOIN dbo.acd_mw_waiver_types t ON t.waiver_type_id=w.waiver_type_id JOIN dbo.acd_mw_waiver_versions v ON v.waiver_version_id=w.waiver_version_id OUTER APPLY(SELECT TOP 1 * FROM dbo.acd_mw_waiver_signatures WHERE waiver_id=w.waiver_id AND signer_type='EMPLOYEE')es OUTER APPLY(SELECT TOP 1 * FROM dbo.acd_mw_waiver_signatures WHERE waiver_id=w.waiver_id AND signer_type='SUPERVISOR')ss WHERE w.waiver_id=?",[$id]);
if(!$w)exit('Waiver not found.');
if(user()['role_name']==='EMPLOYEE'&&(int)(user()['employee_id']??0)!==(int)$w['employee_id']){http_response_code(403);exit('Access denied.');}
if($w['status']!=='COMPLETED'||empty($w['employee_signature'])||empty($w['supervisor_signature'])||empty($w['finalized_at'])||empty($w['document_hash'])){http_response_code(422);exit('Only completed waivers can be printed.');}
$acks=all('SELECT acknowledgment_text FROM dbo.acd_mw_waiver_acknowledgments WHERE waiver_id=? ORDER BY display_order',[$id]);
audit('PRINT_WAIVER','WAIVER',$id,'Formal waiver opened for printing');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><title><?=e($w['waiver_number'])?> — Waiver of Liability</title><style>
@page{size:A4;margin:13mm 16mm}*{box-sizing:border-box}body{font:10.5pt Arial,sans-serif;color:#111;margin:0}.toolbar{position:fixed;right:20px;top:20px;padding:10px 18px}.letterhead{display:grid;grid-template-columns:76px 1fr;gap:12px;align-items:center;border-bottom:2px solid #222;padding-bottom:8px}.letterhead img{width:70px;height:70px;object-fit:contain}.letterhead b{font-size:12pt}.letterhead span{display:block;font-size:8.5pt;line-height:1.35}.title{text-align:center;padding:18px 0 12px}.title h1{font:700 18pt Arial;margin:0 0 6px}.title h2{font-size:10pt;margin:0 0 6px}.meta{display:flex;justify-content:space-between}section{padding:11px 0;border-bottom:1px solid #888}h3{font-size:8.5pt;letter-spacing:.1em;text-transform:uppercase;margin:0 0 9px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:9px 25px}dt{font-size:7.5pt;color:#555;text-transform:uppercase}dd{margin:2px 0;font-weight:bold}.text{line-height:1.55;text-align:justify}.ack{font-size:9pt;margin:6px 0}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:42px}.signatures img{width:100%;height:62px;object-fit:contain;border-bottom:1px solid #111}.signatures b,.signatures small{display:block;text-align:center;margin-top:3px}.hash{font:6.5pt monospace;word-break:break-all}@media print{.toolbar{display:none}}
</style></head><body><button class="toolbar" onclick="window.print()">Print</button>
<div class="letterhead"><img src="/QRS_new/assets/images/la-rose-noire-logo.png" alt="La Rose Noire logo"><div><b>La Rose Noire Philippines, Inc.</b><span>Lot 1 - A &amp; B, Clark IE-05 Area, M.A. Roxas Highway, Clark Freeport Zone, Philippines</span><span>Tel: +63 45 499-3010 · Fax: +63 45 499-2346</span><span>Email: office@la-rose-noire.com</span></div></div>
<div class="title"><h1>WAIVER OF LIABILITY</h1><h2><?=e($w['type_name'])?></h2><div class="meta"><span>Date: <?=e($w['waiver_date'])?></span><span><?=e($w['waiver_number']??'DRAFT')?></span><span>Time: <?=e($w['waiver_time'])?></span></div></div>
<section><h3>Employee information</h3><dl class="grid"><div><dt>Name</dt><dd><?=e($w['employee_name'])?></dd></div><div><dt>Employee number</dt><dd><?=e($w['employee_number'])?></dd></div><div><dt>Department / area</dt><dd><?=e($w['department_name'])?></dd></div><div><dt>Position</dt><dd><?=e($w['position'])?></dd></div></dl></section>
<section><h3>Waiver details</h3><dl class="grid"><div><dt>Medical / nurse personnel</dt><dd><?=e($w['medical_personnel_name'])?></dd></div><div><dt>Transportation offered</dt><dd><?=e($w['transportation_offered'])?></dd></div><div><dt>Recommendation</dt><dd><?=e($w['recommendation'])?></dd></div><div><dt>Remarks</dt><dd><?=e($w['remarks'])?></dd></div></dl></section>
<section><h3>Waiver statement</h3><p class="text"><?=nl2br(e($w['signed_waiver_text']))?></p></section>
<section><h3>Acknowledgments</h3><?php foreach($acks as $a):?><p class="ack">☑ <?=e($a['acknowledgment_text'])?></p><?php endforeach?></section>
<section><h3>Signatures</h3><div class="signatures"><div><img src="<?=e($w['employee_signature'])?>" alt="Employee signature"><b><?=e($w['employee_printed'])?></b><small>Employee Signature over Printed Name · <?=e($w['employee_signed_at'])?></small></div><div><img src="<?=e($w['supervisor_signature'])?>" alt="Supervisor signature"><b><?=e($w['supervisor_printed'])?></b><small>Supervisor Signature over Printed Name · <?=e($w['supervisor_signed_at'])?></small></div></div><p>Finalized: <?=e($w['finalized_at'])?></p><p class="hash">Document hash: <?=e($w['document_hash'])?></p></section>
</body></html>
