<?php
declare(strict_types=1);
const ASSESSMENT_OUTCOMES=['CLEARED_TO_WORK','UNFIT_TO_WORK','ADDITIONAL_MEDICAL_ATTENTION_REQUIRED','HOSPITAL_CONSULTATION_RECOMMENDED','HOSPITAL_TRANSPORT_RECOMMENDED'];
const EMPLOYEE_DECISIONS=['ACCEPTED_RECOMMENDATION','CONTINUE_WORKING','REFUSED_MEDICAL_TREATMENT','REFUSED_HOSPITAL_EVALUATION','REFUSED_TRANSPORT'];
const TRANSPORTATION_OPTIONS=['None','Company Shuttle','Ambulance','Other'];
