<?php
declare(strict_types=1);
const WAIVER_STATUSES=['DRAFT','ASSESSMENT_COMPLETED','EMPLOYEE_DECISION_PENDING','WAIVER_REQUIRED','AWAITING_EMPLOYEE_SIGNATURE','AWAITING_SUPERVISOR','COMPLETED','CANCELLED'];
