USE [LRNPH_OJT]; SET NOCOUNT ON;
-- Fresh-install definitions only. Existing tables are never altered or dropped.
IF OBJECT_ID('dbo.acd_mw_departments','U') IS NULL CREATE TABLE dbo.acd_mw_departments(department_id INT IDENTITY(1,1) PRIMARY KEY,department_code VARCHAR(30) NOT NULL,department_name NVARCHAR(150) NOT NULL,is_active BIT NOT NULL DEFAULT 1,created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME());
IF OBJECT_ID('dbo.acd_mw_employees','U') IS NULL CREATE TABLE dbo.acd_mw_employees(employee_id INT IDENTITY(1,1) PRIMARY KEY,employee_number VARCHAR(30) NOT NULL,first_name NVARCHAR(80) NULL,last_name NVARCHAR(80) NULL,full_name NVARCHAR(180) NOT NULL,department_id INT NOT NULL,position NVARCHAR(150) NULL,email NVARCHAR(180) NULL,is_active BIT NOT NULL DEFAULT 1,created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME());
IF OBJECT_ID('dbo.acd_mw_roles','U') IS NULL CREATE TABLE dbo.acd_mw_roles(role_id INT IDENTITY(1,1) PRIMARY KEY,role_name VARCHAR(50) NOT NULL,description NVARCHAR(300) NULL,created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME());
IF OBJECT_ID('dbo.acd_mw_users','U') IS NULL CREATE TABLE dbo.acd_mw_users(user_id INT IDENTITY(1,1) PRIMARY KEY,username VARCHAR(80) NOT NULL,password_hash VARCHAR(255) NOT NULL,full_name NVARCHAR(180) NOT NULL,email NVARCHAR(180) NULL,role_id INT NOT NULL,employee_id INT NULL,is_active BIT NOT NULL DEFAULT 1,created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME(),updated_at DATETIME2 NULL);
IF OBJECT_ID('dbo.acd_mw_waiver_types','U') IS NULL CREATE TABLE dbo.acd_mw_waiver_types(waiver_type_id INT IDENTITY(1,1) PRIMARY KEY,type_code VARCHAR(80) NOT NULL,type_name NVARCHAR(180) NOT NULL,description NVARCHAR(500) NULL,is_active BIT NOT NULL DEFAULT 1,created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME());
IF OBJECT_ID('dbo.acd_mw_waiver_versions','U') IS NULL CREATE TABLE dbo.acd_mw_waiver_versions(waiver_version_id INT IDENTITY(1,1) PRIMARY KEY,waiver_type_id INT NOT NULL,version_number VARCHAR(20) NOT NULL,waiver_text NVARCHAR(MAX) NOT NULL,status VARCHAR(20) NOT NULL,created_by INT NULL,created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME(),published_at DATETIME2 NULL,retired_at DATETIME2 NULL);
IF OBJECT_ID('dbo.acd_mw_waivers','U') IS NULL CREATE TABLE dbo.acd_mw_waivers(waiver_id INT IDENTITY(1,1) PRIMARY KEY,waiver_number VARCHAR(30) NULL,employee_id INT NOT NULL,waiver_type_id INT NOT NULL,waiver_version_id INT NOT NULL,waiver_date DATE NOT NULL,waiver_time TIME NOT NULL,medical_personnel_name NVARCHAR(150) NULL,recommendation NVARCHAR(1000) NULL,transportation_offered VARCHAR(100) NULL,remarks NVARCHAR(1000) NULL,signed_waiver_text NVARCHAR(MAX) NOT NULL,status VARCHAR(50) NOT NULL,created_by INT NOT NULL,created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME(),finalized_at DATETIME2 NULL,document_hash VARCHAR(64) NULL);
IF OBJECT_ID('dbo.acd_mw_waiver_acknowledgments','U') IS NULL CREATE TABLE dbo.acd_mw_waiver_acknowledgments(acknowledgment_id INT IDENTITY(1,1) PRIMARY KEY,waiver_id INT NOT NULL,acknowledgment_text NVARCHAR(700) NOT NULL,is_acknowledged BIT NOT NULL,display_order INT NOT NULL,acknowledged_at DATETIME2 NOT NULL);
IF OBJECT_ID('dbo.acd_mw_waiver_signatures','U') IS NULL CREATE TABLE dbo.acd_mw_waiver_signatures(signature_id INT IDENTITY(1,1) PRIMARY KEY,waiver_id INT NOT NULL,signer_type VARCHAR(30) NOT NULL,signer_user_id INT NULL,printed_name NVARCHAR(180) NOT NULL,signature_data NVARCHAR(MAX) NOT NULL,ip_address VARCHAR(64) NULL,user_agent NVARCHAR(500) NULL,signed_at DATETIME2 NOT NULL);
IF OBJECT_ID('dbo.acd_mw_activity_logs','U') IS NULL CREATE TABLE dbo.acd_mw_activity_logs(activity_log_id INT IDENTITY(1,1) PRIMARY KEY,user_id INT NULL,action VARCHAR(80) NOT NULL,entity_type VARCHAR(50) NOT NULL,entity_id INT NULL,description NVARCHAR(1000) NULL,ip_address VARCHAR(64) NULL,created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME());
IF OBJECT_ID('dbo.acd_mw_settings','U') IS NULL CREATE TABLE dbo.acd_mw_settings(setting_id INT IDENTITY(1,1) PRIMARY KEY,setting_key VARCHAR(120) NOT NULL,setting_value NVARCHAR(MAX) NULL,updated_by INT NULL,updated_at DATETIME2 NOT NULL DEFAULT SYSDATETIME());
